version: "2"

services:
    mysql:
        image: mysql:5.6
        ports:
            - 10036:3306
        volumes: 
            - ./data/mysql/:/var/lib/mysql
            - ./config/mysql/:/etc/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=root
    php:
        build: ./php
        # volumes:  # TODO 日志
        volumes: 
            # 网站配置
            - ./data/www/:/www/  
            # 日志配置
            - ./logs/php:/var/log/php
  
    nginx: 
        build: ./nginx
        ports: 
            - 8080:80
        links: 
            - php
        depends_on:
            - php
        volumes:
            # ngixn 主配置
            - ./config/nginx/:/etc/nginx/
            # 网站配置
            - ./data/www/:/www/  
            # 日志配置
            - ./logs/nginx/:/var/log/nginx/

